services:
  master_dashboard:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    # Replaced 'build:' with the GHCR image
    image: ghcr.io/laser-power-infra/master_dashboard:${APP_VERSION:-latest}

    container_name: master_dashboard
    ports:
      - "6666:80"

    env_file:
      - .env.production

    environment:
      NODE_ENV: production
      PORT: 80
      HOSTNAME: 0.0.0.0

      

    restart: unless-stopped

    networks:
      - infra



networks:
  infra:
    external: true